### ISSUE TITLE
Error when running `bro-pkg env`

### ISSUE THREAD

**Issue by initconf** [bro/package-manager#1]
```
$ `bro-pkg env`
Traceback (most recent call last):
  File "/usr/local/bin/bro-pkg", line 819, in <module>
    main()
  File "/usr/local/bin/bro-pkg", line 813, in main
    manager = create_manager(config)
  File "/usr/local/bin/bro-pkg", line 120, in create_manager
    plugin_dir=plugin_dir, bro_dist=bro_dist)
  File "/Library/Python/2.7/site-packages/bropkg/manager.py", line 154, in __init__
    os.path.join(self.bropath(), pkg_name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Volumes/home/aashish/.bro-pkg/script_dir/ssn-exposure'
```

**Comment by jsiwek** [comment]
If you update to bro-pkg v0.6 via pip, this may be fixed for you.

But I can't tell exactly how your ~/.bropkg dir ended up in that state.  Did you start with the default bro-pkg configuration, install a package, decide to change your script_dir path in ~/.bropkg/config, but then also manually move or delete some files from within ~/.bropkg/script_dir/ ?

If that's the case, you don't have to manually move files after changing your config file's script_dir path, bro-pkg will automatically relocate all files from previously installed packages.  In general, you should only ever need to touch the config file and never any other files created/installed by bro-pkg.

If it's still broken for you, please give the steps needed to reproduce it from a fresh bro-pkg install.

**Comment by jsiwek** [comment]
If it's still broken for you, re-open the issue and let me know.
