### ISSUE TITLE
configparser dependency not quite right

### ISSUE THREAD

**Issue by JustinAzoff** [bro/package-manager#20]
It looks like the change for:

  * Require extra configparser package only for Python < 3.5 where it is not included (Hilko Bengen)

will work for installing from source, but the resulting dependencies that get built into the whl file are just

```
Requires-Dist: gitpython
Requires-Dist: semantic-version
Requires-Dist: btest
```

so anyone installing bro-pkg from pypi will get a broken installation:

```
jazoff@mbp  /tmp/pp  $ virtualenv  env
New python executable in /private/tmp/pp/env/bin/python2.7
Also creating executable in /private/tmp/pp/env/bin/python
Installing setuptools, pip, wheel...done.
jazoff@mbp  /tmp/pp  $ ./env/bin/pip install bro-pkg
Collecting bro-pkg
  Downloading bro_pkg-1.2-py2.py3-none-any.whl
Collecting gitpython (from bro-pkg)
  Downloading GitPython-2.1.7-py2.py3-none-any.whl (446kB)
    100% |████████████████████████████████| 450kB 2.2MB/s
Collecting btest (from bro-pkg)
  Downloading btest-0.57.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 4.2MB/s
Collecting semantic-version (from bro-pkg)
  Downloading semantic_version-2.6.0.tar.gz
Collecting gitdb2>=2.0.0 (from gitpython->bro-pkg)
  Downloading gitdb2-2.0.3-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 6.7MB/s
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->bro-pkg)
  Downloading smmap2-2.0.3-py2.py3-none-any.whl
Building wheels for collected packages: btest, semantic-version
  Running setup.py bdist_wheel for btest ... done
  Stored in directory: /Users/jazoff/Library/Caches/pip/wheels/2a/fa/f2/f052d23abc1c82c60e660f130e101a8a77ccb68f2070c6a98d
  Running setup.py bdist_wheel for semantic-version ... done
  Stored in directory: /Users/jazoff/Library/Caches/pip/wheels/8e/b7/80/adcc81f7455c6fe108fa530c1dfb5ba037091ff7c633013224
Successfully built btest semantic-version
Installing collected packages: smmap2, gitdb2, gitpython, btest, semantic-version, bro-pkg
Successfully installed bro-pkg-1.2 btest-0.57 gitdb2-2.0.3 gitpython-2.1.7 semantic-version-2.6.0 smmap2-2.0.3
jazoff@mbp  /tmp/pp  $ ./env/bin/bro-pkg
Traceback (most recent call last):
  File "./env/bin/bro-pkg", line 4, in <module>
    from bropkg._util import (
  File "/private/tmp/pp/env/lib/python2.7/site-packages/bropkg/__init__.py", line 18, in <module>
    from .manager import *
  File "/private/tmp/pp/env/lib/python2.7/site-packages/bropkg/manager.py", line 17, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by jsiwek** [comment]
Thanks, this should be fixed now in v1.2.1 on PyPI.

Problem was with building the distribution using Python 3+, but should work now as of this commit: a7fefa6533b508366762deb2d67db67bd1a3ccf1
