### ISSUE TITLE
error when I run bro-pkg refesh

### ISSUE THREAD

**Issue by initconf** [bro/package-manager#3]
I see the following error:

LBL-IPSec-220016:~ aashish$ bro-pkg refresh
Traceback (most recent call last):
  File "/usr/local/bin/bro-pkg", line 819, in <module>
    main()
  File "/usr/local/bin/bro-pkg", line 815, in main
    args.run_cmd(manager, args, config)
  File "/usr/local/bin/bro-pkg", line 239, in cmd_refresh
    src_pkgs_after = {i.qualified_name() for i in manager.source_packages()}
  File "/Library/Python/2.7/site-packages/bropkg/manager.py", line 299, in source_packages
    rval += source.packages()
  File "/Library/Python/2.7/site-packages/bropkg/source.py", line 119, in packages
    parser.read(index_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /Users/aashish/.bro-pkg/clones/source/bro/0xxon/bro-pkg.index, line: 1
'https://github.com/0xxon/bro-sumstats-counttable\n'

**Comment by jsiwek** [comment]
What version of bro-pkg is that?  You can check via `bro-pkg --version`.

v1.0 is the latest.  At some point there was a big change to the format of package metadata/indices and older versions of bro-pkg would probably fail like you're seeing.

If you have bro-pkg installed via pip, you can upgrade via `pip install bro-pkg --upgrade`.

**Comment by initconf** [comment]
This error was from 0.6 version

I have now upgraded. Error is gone !
