### ISSUE TITLE
bro-pkg refresh --aggregate breaks on invalid data

### ISSUE THREAD

**Issue by 0xxon** [bro/package-manager#30]
bro-pkg refresh --aggregate is broken after merging https://github.com/bro/packages/pull/54.

This should probably not happen, even if there is invalid data in these repositories.

Output:

```
$ bro-pkg refresh --aggregate
Refresh package source: bro
Traceback (most recent call last):
  File "/Users/johanna/python/bin/bro-pkg", line 2011, in <module>
    main()
  File "/Users/johanna/python/bin/bro-pkg", line 2007, in main
    args.run_cmd(manager, args, config)
  File "/Users/johanna/python/bin/bro-pkg", line 884, in cmd_refresh
    source, aggregate=args.aggregate, push=args.push)
  File "/Users/johanna/python/lib/python2.7/site-packages/bropkg/manager.py", line 684, in refresh_source
    parser.set(qualified_name, key, value)
  File "/Users/johanna/python/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1239, in set
    super(ConfigParser, self).set(section, option, value)
  File "/Users/johanna/python/lib/python2.7/site-packages/backports/configparser/__init__.py", line 914, in set
    value)
  File "/Users/johanna/python/lib/python2.7/site-packages/backports/configparser/__init__.py", line 392, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in u'(./configure --bro-dist=%(bro_dist) && make)' at position 24
```

**Comment by jsiwek** [comment]
Should be fixed in v1.3.6.
